export enum CHATROOM_TYPE_CODE {
    CARD_NORMAL = 0,
    CARD_INTRO = 1,
    CARD_PRIVATE_EVENT = 2,
    CARD_POLL = 3,
    CARD_FEEDBACK = 4,
    CARD_HIDDEN = 4,
    CARD_PUBLIC_EVENT = 6,
    CARD_PURPOSE = 7,
    CARD_INTRODUCTIONS = 9
}

export enum MESSAGE_STATE {
    NORMAL_MESSAGE = 0,
    FIRST_MESSAGE = 1,
    FOLLOW_TEXT = 2,
    UNFOLLOW_TEXT = 3,
    CHATROOM_TEXT_CREATED = 4,
    GUEST_TEXT = 6
}
