import { OgTag } from './getOgTagResponse';

/* eslint-disable @typescript-eslint/no-explicit-any */
export interface GetConversation {
    chatroomMeta: {
        [key: string]: {
            about: string;
            access: any;
            accessWithoutSubscription: boolean;
            attachmentCount: number;
            attachmentsUploaded: boolean;
            attendingStatus: boolean;
            autoFollowDone: boolean;
            cardId: number;
            chatRequestCreatedAt: any;
            chatRequestState: any;
            chatRequestedById: any;
            chatroomImageUrl: string;
            chatroomWithUserId: any;
            coHosts: string;
            communityId: number;
            createdAt: number;
            customTag: string;
            date: string;
            dateEpoch: number;
            dateTime: number;
            deletedByUserId: any;
            deviceId: string;
            eventKind: string;
            expiryTime: any;
            externalSeen: boolean;
            followStatus: boolean;
            hasBeenNamed: boolean;
            hasFiles: boolean;
            hasReactions: boolean;
            header: string;
            id: number;
            internalLink: any;
            isEdited: boolean;
            isPaid: boolean;
            isPending: boolean;
            isPrivate: boolean;
            isPrivateMember: boolean;
            isSecret: boolean;
            isTagged: boolean;
            lastSeenConversationId: number;
            memberCanMessage: boolean;
            muteStatus: boolean;
            ogTags: any;
            onlineLink: string;
            onlineLinkType: any;
            secretChatroomLeft: boolean;
            secretChatroomParticipants: any;
            shareLink: string;
            state: number;
            title: string;
            type: number;
            updatedAt: number;
            userId: number;
            topicId: any;
        };
    };
    chatroomReactionsMeta: any;
    communityMeta: {
        [key: string]: {
            id: number;
            imageUrl: string;
            isPaid: boolean;
            name: string;
            purpose: string;
            subType: number;
            type: number;
        };
    };
    convAttachmentsMeta: any;
    convPollsMeta: Record<string, PollMeta[]>;
    convReactionsMeta: {
        [key: string]: Array<{
            chatroomId: number;
            conversationId: number;
            id: number;
            reaction: string;
            userId: number;
        }>;
    };
    conversationsData: Array<{
        replyConversationObject: any;
        allowAddOption: boolean;
        answer: string;
        apiVersion: number;
        attachmentCount: number;
        attachmentsUploaded: boolean;
        cardId: number;
        coHosts: any;
        communityId: number;
        createdAt: string;
        createdEpoch: number;
        date: string;
        deletedByUserId: number | string | any;
        deviceId: string;
        endTime: number;
        expiryTime: number | any;
        hasFiles: boolean;
        hasReactions: boolean;
        header: string | any;
        id: number;
        internalLink: any;
        isAnonymous: boolean;
        isEdited: boolean;
        lastUpdated: number;
        location: any;
        locationLat: any;
        locationLong: any;
        multipleSelectNo: number | any;
        multipleSelectState: number | any;
        ogTags: OgTag;
        onlineLinkEnableBefore: number;
        pollAnswerText: string;
        pollType: number;
        pollTypeText: string;
        previewChatroomId: number | any;
        previewCommunityId: number | any;
        previewType: string;
        replyChatroomId: number | any;
        replyId: number | any;
        startTime: number;
        state: number;
        submitTypeText: string | any;
        temporaryId: number | string | any;
        toShowResults: boolean;
        userId: number;
        widgetId: string;
        topicId: number;
    }>;
    userMeta: {
        [key: string]: {
            createdAt: number;
            customTitle: string;
            id: number;
            imageLink: string;
            imageUrl: string | any;
            isGuest: boolean;
            isOwner: boolean;
            name: string;
            sdkClientInfo: {
                communityId: number;
                id: number;
                user: number;
                userUniqueId: string;
                uuid: string;
                widgetId: string;
            };
            state: number;
            userUniqueId: string;
            uuid: string;
        };
    };
    conversationMeta: Record<number | string, ConversationMetaObject>;
    widgets: Record<string, any>;
}

interface ConversationMetaObject {
    allowAddOption: boolean;
    answer: string;
    apiVersion: number;
    attachmentCount: number;
    attachmentsUploaded: boolean;
    cardId: number;
    coHosts: any;
    communityId: number;
    createdAt: string;
    createdEpoch: number;
    date: string;
    deletedByUserId: number | any;
    deviceId: string;
    endTime: number;
    expiryTime: number | any;
    hasFiles: boolean;
    hasReactions: boolean;
    header: string | any;
    id: number;
    internalLink: any;
    isAnonymous: boolean;
    isEdited: boolean;
    lastUpdated: number;
    location: any;
    locationLat: any;
    locationLong: any;
    multipleSelectNo: number | any;
    multipleSelectState: number | any;
    ogTags: OgTag | any;
    onlineLinkEnableBefore: number;
    pollAnswerText: string;
    pollType: number | any;
    pollTypeText: any;
    previewChatroomId: any;
    previewCommunityId: any;
    previewType: string;
    replyChatroomId: number | any;
    replyId: number | any;
    startTime: number;
    state: number;
    submitTypeText: string | any;
    temporaryId: number | any;
    toShowResults: boolean;
    userId: number;
    widgetId: string;
    topicId: number;
}
interface PollMeta {
    conversationId: number;
    count: any | number;
    id: number;
    isSelected: boolean;
    noVotes: number;
    percentage: any | number;
    text: string;
    userId: number;
}
