export const API = {
  SDK_RESOURCE: "/sdk/initiate",
  MY_CHATOOMS: "/v1/my_chatrooms",
  CHATROOM_FETCH: "/chatroom/fetch",
  CONVERSATION_FETCH: "/conversation/fetch",
  CONVERSATION_CREATE: "/conversation/create",
  CONVERSATION_ADD_ACTION: "/conversation/add_reaction",
  CHATROOM_GET_TAGGINNG_LIST: "/chatroom/get_tagging_list",
  FETCH_REPORT_TAGS: "/fetch_report_tags",
  PUSH_REPORT: "/push_report",
  COLLABCARD_FOLLOW: "/collabcard_follow",
  UPLOAD_FILES: "/v1/upload_files",
  MEMBER_STATE: "/members_state",
  COMMUNITY_MEMBER_FETCH_FEED: "/community_member/fetch_feed",
  ALL_MEMBERS: "/v1/all_members",
  MARK_READ: "/mark_read",
  COLLABCARD_SEEN: "/collabcard_seen",
  FETCH_DM_FEED: "/user/fetch_dm_feed",
  CAN_DM: "/community_member/can_dm",
  FETCH_DM_CHATROOMS: "/community_member/fetch_dm_chatrooms",
};
